name: Release
on:
  push:
    tags:
    - 'v*'
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create release artifacts
      run: VERSION=$(awk -F '/' '{print $3}'<<< "$GITHUB_REF") make release
    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=$(awk -F '/' '{print $3}'<<< "$GITHUB_REF")
        for f in ./build/artifacts/*
        do
          [ -f "$f" ] && assets+=(-a "$f")
        done
        hub release create -m "Release ${VERSION}" \
          "${assets[@]}" "${VERSION}"
